export const areaCharts = {
  id: "area",
  label: "Area",
  iconKey: "area",
  categories: ["trend", "comparison"],
  description: "Filled trend charts for volume, contribution, and range storytelling.",
  variants: [
    {
      id: "basic-area-variant",
      label: "Basic Area",
      description: "Single-series area trend chart.",
      family: "area",
      exampleKey: "basic-area-variant",
      chartId: "area",
      requiredRoles: ["x", "y"],
      optionalRoles: ["series", "ys"],
      renderingStrategy: "area",
      supportLevel: "supported",
    },
    {
      id: "stacked-area-variant",
      label: "Stacked Area",
      description: "Stacked areas to compare total plus composition.",
      family: "area",
      exampleKey: "stacked-area-variant",
      chartId: "stacked-area",
      requiredRoles: ["x", "y"],
      optionalRoles: ["series", "ys"],
      renderingStrategy: "stacked-area",
      supportLevel: "supported",
    },
    {
      id: "gradient-area-variant",
      label: "Gradient Area",
      description: "Area chart with gradient emphasis.",
      family: "area",
      exampleKey: "gradient-area-variant",
      chartId: "area",
      requiredRoles: ["x", "y"],
      optionalRoles: ["series", "ys"],
      renderingStrategy: "area",
      supportLevel: "partial",
    },
    {
      id: "multi-area-variant",
      label: "Multi Area",
      description: "Multiple area series across one axis.",
      family: "area",
      exampleKey: "multi-area-variant",
      chartId: "area",
      requiredRoles: ["x", "y"],
      optionalRoles: ["series", "ys"],
      renderingStrategy: "area",
      supportLevel: "supported",
    },
    {
      id: "range-area-variant",
      label: "Range Area",
      description: "Range-style area using multiple value bands.",
      family: "area",
      exampleKey: "range-area-variant",
      chartId: "area",
      requiredRoles: ["x", "y"],
      optionalRoles: ["ys", "series"],
      renderingStrategy: "area",
      supportLevel: "partial",
    },
  ],
};

export default areaCharts;
