export const bubbleCharts = {
  id: "bubble",
  label: "Bubble",
  iconKey: "bubble",
  categories: ["relationship", "distribution"],
  description: "Third-metric point charts for size and performance comparisons.",
  variants: [
    {
      id: "basic-bubble-variant",
      label: "Basic Bubble",
      description: "Bubble chart with X, Y, and bubble size.",
      family: "bubble",
      exampleKey: "basic-bubble-variant",
      chartId: "bubble",
      requiredRoles: ["x", "y", "size"],
      optionalRoles: ["series", "label"],
      renderingStrategy: "bubble",
      supportLevel: "supported",
    },
    {
      id: "multi-bubble-variant",
      label: "Multi Bubble",
      description: "Multiple bubble series in one plot.",
      family: "bubble",
      exampleKey: "multi-bubble-variant",
      chartId: "bubble",
      requiredRoles: ["x", "y", "size"],
      optionalRoles: ["series", "label"],
      renderingStrategy: "bubble",
      supportLevel: "supported",
    },
    {
      id: "performance-bubble-variant",
      label: "Performance Bubble",
      description: "Bubble view for performance quadrant analysis.",
      family: "bubble",
      exampleKey: "performance-bubble-variant",
      chartId: "bubble",
      requiredRoles: ["x", "y", "size"],
      optionalRoles: ["series", "label"],
      renderingStrategy: "bubble",
      supportLevel: "partial",
    },
    {
      id: "size-bubble-variant",
      label: "Size Bubble",
      description: "Emphasize relative size contribution by mark radius.",
      family: "bubble",
      exampleKey: "size-bubble-variant",
      chartId: "bubble",
      requiredRoles: ["x", "y", "size"],
      optionalRoles: ["series", "label"],
      renderingStrategy: "bubble",
      supportLevel: "supported",
    },
  ],
};

export default bubbleCharts;
