export const mixedCharts = {
  id: "mixed",
  label: "Mixed",
  iconKey: "mixed",
  categories: ["comparison", "trend"],
  description: "Combination views that blend bars and lines for multi-metric stories.",
  variants: [
    {
      id: "bar-line-mixed-variant",
      label: "Bar + Line",
      description: "Combine bars with a trend line.",
      family: "mixed",
      exampleKey: "bar-line-mixed-variant",
      chartId: "mixed-line-bar",
      requiredRoles: ["category", "value"],
      optionalRoles: ["values", "series"],
      renderingStrategy: "mixed",
      supportLevel: "supported",
    },
    {
      id: "dual-axis-mixed-variant",
      label: "Dual Axis",
      description: "Compare two measures with separate scales.",
      family: "mixed",
      exampleKey: "dual-axis-mixed-variant",
      chartId: "mixed-line-bar",
      requiredRoles: ["category", "value"],
      optionalRoles: ["values", "series"],
      renderingStrategy: "mixed",
      supportLevel: "partial",
    },
    {
      id: "kpi-line-mixed-variant",
      label: "KPI + Line",
      description: "Primary KPI bars plus a companion trend line.",
      family: "mixed",
      exampleKey: "kpi-line-mixed-variant",
      chartId: "mixed-line-bar",
      requiredRoles: ["category", "value"],
      optionalRoles: ["values", "series"],
      renderingStrategy: "mixed",
      supportLevel: "partial",
    },
    {
      id: "stacked-line-mixed-variant",
      label: "Stacked + Line",
      description: "Stacked bars with an overlay line comparison.",
      family: "mixed",
      exampleKey: "stacked-line-mixed-variant",
      chartId: "mixed-line-bar",
      requiredRoles: ["category", "value"],
      optionalRoles: ["values", "series"],
      renderingStrategy: "mixed",
      supportLevel: "partial",
    },
    {
      id: "comparison-mixed-variant",
      label: "Combo Comparison",
      description: "Comparison-focused combination chart.",
      family: "mixed",
      exampleKey: "comparison-mixed-variant",
      chartId: "mixed-line-bar",
      requiredRoles: ["category", "value"],
      optionalRoles: ["values", "series"],
      renderingStrategy: "mixed",
      supportLevel: "supported",
    },
  ],
};

export default mixedCharts;
