export const scatterCharts = {
  id: "scatter",
  label: "Scatter",
  iconKey: "scatter",
  categories: ["distribution", "relationship", "geo"],
  description: "Correlation, point distribution, bubble, and geo-scatter views.",
  variants: [
    { id: "basic-scatter-chart", label: "Basic Scatter Chart", description: "Two-measure scatter plot.", family: "scatter", exampleKey: "basic-scatter-chart", chartId: "scatter", requiredRoles: ["x", "y"], optionalRoles: ["series", "size"], renderingStrategy: "scatter", supportLevel: "supported" },
    { id: "anscombs-quartet", label: "Anscomb's quartet", description: "Same summary stats, different distributions.", family: "scatter", exampleKey: "anscombs-quartet", chartId: "scatter", requiredRoles: ["x", "y"], optionalRoles: ["series"], renderingStrategy: "scatter", supportLevel: "partial" },
    { id: "clustering-process", label: "Clustering Process", description: "Scatter prepared for clustering animation.", family: "scatter", exampleKey: "clustering-process", chartId: "scatter", requiredRoles: ["x", "y"], optionalRoles: ["series", "size"], renderingStrategy: "scatter", supportLevel: "metadata-ready" },
    { id: "exponential-regression", label: "Exponential Regression", description: "Scatter with regression overlay.", family: "scatter", exampleKey: "exponential-regression", chartId: "scatter", requiredRoles: ["x", "y"], optionalRoles: ["series"], renderingStrategy: "scatter", supportLevel: "partial" },
    { id: "effect-scatter-chart", label: "Effect Scatter Chart", description: "Ripple-highlighted scatter points.", family: "scatter", exampleKey: "effect-scatter-chart", chartId: "effect-scatter", requiredRoles: ["x", "y"], optionalRoles: ["series", "size"], renderingStrategy: "scatter", supportLevel: "supported" },
    { id: "linear-regression", label: "Linear Regression", description: "Scatter with linear regression support.", family: "scatter", exampleKey: "linear-regression", chartId: "scatter", requiredRoles: ["x", "y"], optionalRoles: ["series"], renderingStrategy: "scatter", supportLevel: "partial" },
    { id: "polynomial-regression", label: "Polynomial Regression", description: "Scatter with polynomial regression.", family: "scatter", exampleKey: "polynomial-regression", chartId: "scatter", requiredRoles: ["x", "y"], optionalRoles: ["series"], renderingStrategy: "scatter", supportLevel: "metadata-ready" },
    { id: "scatter-jittering", label: "Scatter with Jittering", description: "Spread dense points with jitter.", family: "scatter", exampleKey: "scatter-jittering", chartId: "scatter", requiredRoles: ["x", "y"], optionalRoles: ["series"], renderingStrategy: "scatter", supportLevel: "partial" },
    { id: "github-punch-card", label: "Punch Card of Github", description: "Single-axis scatter density layout.", family: "scatter", exampleKey: "github-punch-card", chartId: "scatter", requiredRoles: ["x", "y"], optionalRoles: ["size"], renderingStrategy: "scatter", supportLevel: "partial" },
    { id: "scatter-single-axis", label: "Scatter on Single Axis", description: "Single-axis scatter arrangement.", family: "scatter", exampleKey: "scatter-single-axis", chartId: "scatter", requiredRoles: ["x", "y"], optionalRoles: ["size"], renderingStrategy: "scatter", supportLevel: "partial" },
    { id: "height-weight-distribution", label: "Distribution of Height and Weight", description: "Height/weight bubble scatter.", family: "scatter", exampleKey: "height-weight-distribution", chartId: "bubble", requiredRoles: ["x", "y", "size"], optionalRoles: ["series"], renderingStrategy: "scatter", supportLevel: "supported" },
    { id: "aggregate-scatter-bar", label: "Aggregate Scatter to Bar", description: "Aggregate scatter patterns into bars.", family: "scatter", exampleKey: "aggregate-scatter-bar", chartId: "scatter", requiredRoles: ["x", "y"], optionalRoles: ["series"], renderingStrategy: "scatter", supportLevel: "metadata-ready" },
    { id: "align-label-top", label: "Align Label on the Top", description: "Label alignment around scatter marks.", family: "scatter", exampleKey: "align-label-top", chartId: "scatter", requiredRoles: ["x", "y"], optionalRoles: ["label"], renderingStrategy: "scatter", supportLevel: "partial" },
    { id: "symbol-shape-morph", label: "Symbol Shape Morph", description: "Animated symbol morphing.", family: "scatter", exampleKey: "symbol-shape-morph", chartId: "effect-scatter", requiredRoles: ["x", "y"], optionalRoles: ["size"], renderingStrategy: "scatter", supportLevel: "metadata-ready" },
    { id: "large-scatter", label: "Large Scatter", description: "Prepared for denser point sets.", family: "scatter", exampleKey: "large-scatter", chartId: "large-scatter", requiredRoles: ["x", "y"], optionalRoles: ["series", "size"], renderingStrategy: "scatter", supportLevel: "supported" },
    { id: "scatter-nebula", label: "Scatter Nebula", description: "Aesthetic scatter clustering view.", family: "scatter", exampleKey: "scatter-nebula", chartId: "scatter", requiredRoles: ["x", "y"], optionalRoles: ["series", "size"], renderingStrategy: "scatter", supportLevel: "metadata-ready" },
    { id: "visual-interaction-stream", label: "Visual interaction with stream", description: "Interactive scatter filtering/streaming concept.", family: "scatter", exampleKey: "visual-interaction-stream", chartId: "scatter", requiredRoles: ["x", "y"], optionalRoles: ["series"], renderingStrategy: "scatter", supportLevel: "metadata-ready" },
    { id: "bubble-chart", label: "Bubble Chart", description: "Scatter with size as a third measure.", family: "scatter", exampleKey: "bubble-chart", chartId: "bubble", requiredRoles: ["x", "y", "size"], optionalRoles: ["series"], renderingStrategy: "scatter", supportLevel: "supported" },
    { id: "scatter-aqi-color", label: "Scatter Aqi Color", description: "AQI scatter with visual color encoding.", family: "scatter", exampleKey: "scatter-aqi-color", chartId: "scatter", requiredRoles: ["x", "y"], optionalRoles: ["series", "size"], renderingStrategy: "scatter", supportLevel: "partial" },
    { id: "scatter-nutrients", label: "Scatter Nutrients", description: "Nutrition scatter comparison.", family: "scatter", exampleKey: "scatter-nutrients", chartId: "scatter", requiredRoles: ["x", "y"], optionalRoles: ["size", "series"], renderingStrategy: "scatter", supportLevel: "supported" },
    { id: "scatter-nutrients-matrix", label: "Scatter Nutrients Matrix", description: "Matrix-like nutrient scatter comparisons.", family: "scatter", exampleKey: "scatter-nutrients-matrix", chartId: "matrix", requiredRoles: ["row", "column", "value"], optionalRoles: ["series"], renderingStrategy: "matrix", supportLevel: "metadata-ready" },
    { id: "life-expectancy-gdp", label: "Life Expectancy and GDP", description: "Bubble chart for GDP/life expectancy.", family: "scatter", exampleKey: "life-expectancy-gdp", chartId: "bubble", requiredRoles: ["x", "y", "size"], optionalRoles: ["series"], renderingStrategy: "scatter", supportLevel: "supported" },
    { id: "master-painter-colors", label: "Master Painter Color Choices Throughout History", description: "High-dimensional scatter storytelling.", family: "scatter", exampleKey: "master-painter-colors", chartId: "scatter", requiredRoles: ["x", "y"], optionalRoles: ["series", "detail"], renderingStrategy: "scatter", supportLevel: "metadata-ready" },
    { id: "logarithmic-regression", label: "Logarithmic Regression", description: "Scatter with log regression model.", family: "scatter", exampleKey: "logarithmic-regression", chartId: "scatter", requiredRoles: ["x", "y"], optionalRoles: ["series"], renderingStrategy: "scatter", supportLevel: "metadata-ready" },
    { id: "geo-choropleth-scatter", label: "Geo Choropleth and Scatter", description: "Map with scatter overlays.", family: "scatter", exampleKey: "geo-choropleth-scatter", chartId: "geo-scatter", requiredRoles: ["region", "value"], optionalRoles: ["series", "size"], renderingStrategy: "map-scatter", supportLevel: "partial" },
    { id: "scatter-matrix", label: "Scatter Matrix", description: "Matrix-style scatter comparison.", family: "scatter", exampleKey: "scatter-matrix", chartId: "matrix", requiredRoles: ["row", "column", "value"], optionalRoles: ["series"], renderingStrategy: "matrix", supportLevel: "metadata-ready" },
    { id: "calendar-charts", label: "Calendar Charts", description: "Scatter marks inside a calendar layout.", family: "scatter", exampleKey: "calendar-charts", chartId: "calendar", requiredRoles: ["date", "value"], optionalRoles: ["series"], renderingStrategy: "calendar-scatter", supportLevel: "metadata-ready" }
  ]
};

export default scatterCharts;
