import type { ChartPreset } from "./demoTypes";

export const chartPresets: ChartPreset[] = [
  {
    id: "monthly-sales-bar",
    name: "ยอดขายรายเดือน",
    description: "กราฟแท่งสำหรับเล่า trend ยอดขายตามเดือน",
    chartType: "bar",
    chartTypes: ["bar", "column", "clustered-bar", "grouped-column"],
    themeId: "default-blue",
    sort: "monthOrder",
    badge: "แนะนำ",
    mappings: [
      { slotId: "xAxis", fieldIds: ["month"], aggregation: "None" },
      { slotId: "yAxis", fieldIds: ["sales"], aggregation: "Sum" },
      { slotId: "tooltip", fieldIds: ["profit", "quantity"], aggregation: "Sum" },
      { slotId: "value", fieldIds: ["sales"], aggregation: "Sum" },
    ],
    settings: {
      general: { title: "ยอดขายรายเดือน", subtitle: "ยอดขายรวมจากข้อมูลเดโม" },
      legend: { showLegend: false },
      axis: { xAxisLabel: "เดือน", yAxisLabel: "ยอดขาย" },
    },
  },
  {
    id: "monthly-sales-profit",
    name: "ยอดขายเทียบกำไร",
    description: "เปรียบเทียบยอดขายและกำไรในชุดเดียว",
    chartType: "bar",
    chartTypes: ["bar", "column", "clustered-bar", "grouped-column"],
    themeId: "business-green",
    sort: "monthOrder",
    mappings: [
      { slotId: "xAxis", fieldIds: ["month"], aggregation: "None" },
      { slotId: "yAxis", fieldIds: ["sales", "profit"], aggregation: "Sum" },
      { slotId: "tooltip", fieldIds: ["cost", "target"], aggregation: "Sum" },
    ],
    settings: {
      general: { title: "ยอดขายเทียบกำไร", subtitle: "เหมาะสำหรับดู margin เบื้องต้น" },
      legend: { showLegend: true, position: "top", align: "center" },
      axis: { xAxisLabel: "เดือน", yAxisLabel: "มูลค่า" },
    },
  },
  {
    id: "channel-stacked-sales",
    name: "ยอดขายตามช่องทาง",
    description: "Stacked chart สำหรับเห็น mix ช่องทางขาย",
    chartType: "stacked-bar",
    chartTypes: ["stacked-bar", "stacked-column", "100-percent-stacked-bar", "100-percent-stacked-column"],
    themeId: "warm-orange",
    sort: "monthOrder",
    badge: "เดโม",
    mappings: [
      { slotId: "xAxis", fieldIds: ["month"], aggregation: "None" },
      { slotId: "yAxis", fieldIds: ["sales"], aggregation: "Sum" },
      { slotId: "legend", fieldIds: ["channel"], aggregation: "None" },
      { slotId: "tooltip", fieldIds: ["profit", "quantity"], aggregation: "Sum" },
      { slotId: "value", fieldIds: ["sales"], aggregation: "Sum" },
    ],
    settings: {
      general: { title: "ยอดขายตามช่องทาง", subtitle: "แยกยอดขายตาม channel" },
      legend: { showLegend: true, position: "bottom", align: "center" },
    },
  },
  {
    id: "trend-line-profit",
    name: "แนวโน้มกำไร",
    description: "Line chart สำหรับติดตามกำไรตามเดือน",
    chartType: "line",
    chartTypes: ["line", "multi-line", "time-series-line"],
    themeId: "business-green",
    sort: "monthOrder",
    mappings: [
      { slotId: "xAxis", fieldIds: ["month"], aggregation: "None" },
      { slotId: "yAxis", fieldIds: ["profit"], aggregation: "Sum" },
      { slotId: "tooltip", fieldIds: ["sales", "cost"], aggregation: "Sum" },
    ],
    settings: {
      general: { title: "แนวโน้มกำไรรายเดือน", subtitle: "ใช้ดู momentum ของกำไร" },
      legend: { showLegend: false },
      axis: { xAxisLabel: "เดือน", yAxisLabel: "กำไร" },
    },
  },
  {
    id: "area-target-progress",
    name: "ยอดขายเทียบเป้าหมาย",
    description: "Area chart สำหรับเล่าความคืบหน้าสะสม",
    chartType: "area",
    chartTypes: ["area", "stacked-area"],
    themeId: "default-blue",
    sort: "monthOrder",
    mappings: [
      { slotId: "xAxis", fieldIds: ["month"], aggregation: "None" },
      { slotId: "yAxis", fieldIds: ["sales", "target"], aggregation: "Sum" },
      { slotId: "tooltip", fieldIds: ["profit"], aggregation: "Sum" },
    ],
    settings: {
      general: { title: "ยอดขายเทียบเป้าหมาย", subtitle: "พื้นที่แสดงภาพรวมเป้าหมาย" },
      legend: { showLegend: true, position: "top", align: "center" },
    },
  },
  {
    id: "sales-share-category",
    name: "สัดส่วนยอดขายตามหมวดหมู่",
    description: "Preset สำหรับ Donut/Pie ที่ใช้ใน flow เดโมขาย",
    chartType: "donut",
    chartTypes: ["donut", "pie", "treemap", "polar-area"],
    themeId: "premium-purple",
    sort: "byValueDescending",
    badge: "ขายดี",
    mappings: [
      { slotId: "category", fieldIds: ["category"], aggregation: "None" },
      { slotId: "legend", fieldIds: ["category"], aggregation: "None" },
      { slotId: "value", fieldIds: ["sales"], aggregation: "Sum" },
      { slotId: "yAxis", fieldIds: ["sales"], aggregation: "Sum" },
      { slotId: "tooltip", fieldIds: ["profit", "quantity"], aggregation: "Sum" },
    ],
    settings: {
      general: { title: "สัดส่วนยอดขายตามหมวดหมู่", subtitle: "แสดง contribution ของแต่ละหมวดสินค้า" },
      legend: { showLegend: true, position: "right", align: "center" },
      labels: { showDataLabels: true, position: "outside", fontSize: 11 },
    },
  },
  {
    id: "profit-vs-cost-scatter",
    name: "ยอดขายเทียบกำไร",
    description: "Scatter สำหรับดูความสัมพันธ์ระหว่างยอดขายและกำไร",
    chartType: "scatter",
    chartTypes: ["scatter", "bubble", "correlation-scatter"],
    themeId: "minimal-gray",
    sort: "none",
    mappings: [
      { slotId: "xAxis", fieldIds: ["sales"], aggregation: "Sum" },
      { slotId: "yAxis", fieldIds: ["profit"], aggregation: "Sum" },
      { slotId: "size", fieldIds: ["quantity"], aggregation: "Sum" },
      { slotId: "color", fieldIds: ["category"], aggregation: "None" },
      { slotId: "tooltip", fieldIds: ["channel", "product"], aggregation: "None" },
    ],
    settings: {
      general: { title: "ยอดขายเทียบกำไร", subtitle: "ตรวจจุดที่ยอดขายสูงแต่กำไรต่ำ" },
      legend: { showLegend: true, position: "bottom", align: "center" },
      axis: { xAxisLabel: "ยอดขาย", yAxisLabel: "กำไร" },
    },
  },
  {
    id: "total-sales-kpi",
    name: "KPI ยอดขายรวม",
    description: "KPI card สำหรับสรุปยอดขายและเป้าหมาย",
    chartType: "kpi-card",
    chartTypes: ["kpi-card", "metric-card", "scorecard", "gauge", "progress-ring"],
    themeId: "executive-dark",
    badge: "แนะนำ",
    mappings: [
      { slotId: "value", fieldIds: ["sales"], aggregation: "Sum" },
      { slotId: "target", fieldIds: ["target"], aggregation: "Sum" },
      { slotId: "tooltip", fieldIds: ["profit"], aggregation: "Sum" },
    ],
    settings: {
      general: { title: "ยอดขายรวม", subtitle: "KPI พร้อมเป้าหมาย" },
      legend: { showLegend: false },
      grid: { showGrid: false },
    },
  },
  {
    id: "finance-table",
    name: "ตารางยอดขายและกำไร",
    description: "Table preset สำหรับ export CSV และตรวจรายละเอียด",
    chartType: "table",
    chartTypes: ["table", "summary-table", "pivot-table", "matrix-table"],
    themeId: "minimal-gray",
    sort: "monthOrder",
    mappings: [
      { slotId: "rows", fieldIds: ["month", "category", "channel", "sales", "profit", "cost"], aggregation: "None" },
      { slotId: "value", fieldIds: ["sales", "profit", "cost"], aggregation: "Sum" },
      { slotId: "columns", fieldIds: ["category"], aggregation: "None" },
    ],
    settings: {
      general: { title: "ตารางยอดขายและกำไร", subtitle: "รายละเอียดสำหรับตรวจสอบและส่งออก CSV" },
      legend: { showLegend: false },
    },
  },
];

export function getPresetsForChart(chartType: ChartPreset["chartType"] | null) {
  if (!chartType) return chartPresets;
  return chartPresets.filter((preset) => preset.chartTypes.includes(chartType));
}
