function role(key, label, accepts, multiple = false) {
  return {
    key,
    label,
    accepts,
    multiple,
  };
}

function createTemplate({
  id,
  family,
  variant,
  type,
  name,
  description,
  requiredRoles,
  roles,
  defaultMapping,
  defaultSettings,
}) {
  return {
    id,
    engine: "chartjs",
    family,
    variant,
    type,
    name,
    description,
    requiredRoles,
    roles,
    defaultMapping,
    defaultSettings,
  };
}

const roleSets = {
  categoryValue: [
    role("x", "Category", ["category", "date"]),
    role("y", "Value", ["number"]),
    role("series", "Series", ["category"]),
  ],
  floatingBar: [
    role("x", "Category", ["category", "date"]),
    role("min", "Min", ["number"]),
    role("max", "Max", ["number"]),
    role("series", "Series", ["category"]),
  ],
  multiLine: [
    role("x", "X Axis", ["category", "date"]),
    role("y", "Value", ["number"]),
    role("series", "Series", ["category"]),
    role("measures", "Measures", ["number"], true),
  ],
  lineMeasures: [
    role("x", "X Axis", ["category", "date"]),
    role("measures", "Measures", ["number"], true),
  ],
  pie: [
    role("label", "Label", ["category"]),
    role("value", "Value", ["number"]),
    role("measures", "Measures", ["number"], true),
  ],
  radar: [
    role("label", "Label", ["category"]),
    role("value", "Value", ["number"]),
    role("series", "Series", ["category"]),
    role("measures", "Measures", ["number"], true),
  ],
  scatter: [
    role("x", "X Value", ["number"]),
    role("y", "Y Value", ["number"]),
    role("series", "Series", ["category"]),
  ],
  bubble: [
    role("x", "X Value", ["number"]),
    role("y", "Y Value", ["number"]),
    role("size", "Bubble Size", ["number"]),
    role("series", "Series", ["category"]),
  ],
  mixed: [
    role("x", "Category", ["category", "date"]),
    role("bar", "Bar Value", ["number"]),
    role("line", "Line Value", ["number"]),
    role("series", "Series", ["category"]),
  ],
};

export const chartJsTemplates = [
  createTemplate({
    id: "bar-vertical",
    family: "bar",
    variant: "vertical",
    type: "bar",
    name: "Vertical Bar",
    description: "Compare a numeric value across categories.",
    requiredRoles: ["x", "y"],
    roles: roleSets.categoryValue,
    defaultMapping: { x: "month", y: "sales", series: null },
    defaultSettings: { aggregation: "sum", horizontal: false, stacked: false, legendPosition: "bottom", showLegend: true, beginAtZero: true },
  }),
  createTemplate({
    id: "bar-horizontal",
    family: "bar",
    variant: "horizontal",
    type: "bar",
    name: "Horizontal Bar",
    description: "Compare values across categories with horizontal bars.",
    requiredRoles: ["x", "y"],
    roles: roleSets.categoryValue,
    defaultMapping: { x: "region", y: "profit", series: null },
    defaultSettings: { aggregation: "sum", horizontal: true, stacked: false, legendPosition: "bottom", showLegend: true, beginAtZero: true },
  }),
  createTemplate({
    id: "bar-stacked",
    family: "bar",
    variant: "stacked",
    type: "bar",
    name: "Stacked Bar",
    description: "Show composition inside each category.",
    requiredRoles: ["x", "y", "series"],
    roles: roleSets.categoryValue,
    defaultMapping: { x: "month", y: "sales", series: "category" },
    defaultSettings: { aggregation: "sum", horizontal: false, stacked: true, legendPosition: "bottom", showLegend: true, beginAtZero: true },
  }),
  createTemplate({
    id: "bar-grouped",
    family: "bar",
    variant: "grouped",
    type: "bar",
    name: "Grouped Bar",
    description: "Compare grouped categories side by side.",
    requiredRoles: ["x", "y", "series"],
    roles: roleSets.categoryValue,
    defaultMapping: { x: "month", y: "sales", series: "region" },
    defaultSettings: { aggregation: "sum", horizontal: false, stacked: false, legendPosition: "bottom", showLegend: true, beginAtZero: true },
  }),
  createTemplate({
    id: "bar-floating",
    family: "bar",
    variant: "floating",
    type: "bar",
    name: "Floating Bar",
    description: "Display a range between min and max values.",
    requiredRoles: ["x", "min", "max"],
    roles: roleSets.floatingBar,
    defaultMapping: { x: "region", min: "minRange", max: "maxRange", series: null },
    defaultSettings: { aggregation: "avg", horizontal: false, stacked: false, legendPosition: "bottom", showLegend: true, beginAtZero: false },
  }),
  createTemplate({
    id: "line-basic",
    family: "line",
    variant: "basic",
    type: "line",
    name: "Basic Line",
    description: "Track a numeric trend across an ordered dimension.",
    requiredRoles: ["x", "y"],
    roles: roleSets.categoryValue,
    defaultMapping: { x: "date", y: "sales", series: null },
    defaultSettings: { aggregation: "sum", smooth: false, stepped: false, legendPosition: "bottom", showLegend: true, beginAtZero: true },
  }),
  createTemplate({
    id: "line-multi",
    family: "line",
    variant: "multi",
    type: "line",
    name: "Multi Line",
    description: "Render multiple trend lines by series or measure.",
    requiredRoles: ["x"],
    roles: roleSets.multiLine,
    defaultMapping: { x: "date", y: "sales", series: "region", measures: ["sales", "profit"] },
    defaultSettings: { aggregation: "sum", smooth: false, stepped: false, legendPosition: "bottom", showLegend: true, beginAtZero: true },
  }),
  createTemplate({
    id: "line-stepped",
    family: "line",
    variant: "stepped",
    type: "line",
    name: "Stepped Line",
    description: "Show discrete changes between points.",
    requiredRoles: ["x", "y"],
    roles: roleSets.categoryValue,
    defaultMapping: { x: "month", y: "orders", series: null },
    defaultSettings: { aggregation: "sum", smooth: false, stepped: true, legendPosition: "bottom", showLegend: true, beginAtZero: true },
  }),
  createTemplate({
    id: "line-curved",
    family: "line",
    variant: "curved",
    type: "line",
    name: "Curved Line",
    description: "Use a smoothed line for softer trend emphasis.",
    requiredRoles: ["x", "y"],
    roles: roleSets.categoryValue,
    defaultMapping: { x: "date", y: "profit", series: null },
    defaultSettings: { aggregation: "sum", smooth: true, stepped: false, legendPosition: "bottom", showLegend: true, beginAtZero: true },
  }),
  createTemplate({
    id: "line-multi-axis",
    family: "line",
    variant: "multi-axis",
    type: "line",
    name: "Multi Axis Line",
    description: "Plot two or more measures on separate axes.",
    requiredRoles: ["x", "measures"],
    roles: roleSets.lineMeasures,
    defaultMapping: { x: "date", measures: ["sales", "profit"] },
    defaultSettings: { aggregation: "sum", smooth: false, stepped: false, legendPosition: "bottom", showLegend: true, beginAtZero: true, useSecondaryAxis: true },
  }),
  createTemplate({
    id: "area-basic",
    family: "area",
    variant: "basic",
    type: "line",
    name: "Basic Area",
    description: "Highlight volume with a filled area.",
    requiredRoles: ["x", "y"],
    roles: roleSets.categoryValue,
    defaultMapping: { x: "date", y: "sales", series: null },
    defaultSettings: { aggregation: "sum", area: true, stacked: false, smooth: false, legendPosition: "bottom", showLegend: true, beginAtZero: true },
  }),
  createTemplate({
    id: "area-stacked",
    family: "area",
    variant: "stacked",
    type: "line",
    name: "Stacked Area",
    description: "Show total volume and contribution by series.",
    requiredRoles: ["x", "y", "series"],
    roles: roleSets.categoryValue,
    defaultMapping: { x: "date", y: "sales", series: "category" },
    defaultSettings: { aggregation: "sum", area: true, stacked: true, smooth: false, legendPosition: "bottom", showLegend: true, beginAtZero: true },
  }),
  createTemplate({
    id: "area-filled-line",
    family: "area",
    variant: "filled-line",
    type: "line",
    name: "Filled Line Area",
    description: "A smoother filled line treatment for trend emphasis.",
    requiredRoles: ["x", "y"],
    roles: roleSets.categoryValue,
    defaultMapping: { x: "date", y: "profit", series: null },
    defaultSettings: { aggregation: "sum", area: true, stacked: false, smooth: true, legendPosition: "bottom", showLegend: true, beginAtZero: true },
  }),
  createTemplate({
    id: "pie-basic",
    family: "pie",
    variant: "pie",
    type: "pie",
    name: "Pie",
    description: "Show a part-to-whole breakdown.",
    requiredRoles: ["label", "value"],
    roles: roleSets.pie,
    defaultMapping: { label: "category", value: "sales" },
    defaultSettings: { aggregation: "sum", legendPosition: "right", showLegend: true },
  }),
  createTemplate({
    id: "doughnut-basic",
    family: "doughnut",
    variant: "basic",
    type: "doughnut",
    name: "Doughnut",
    description: "A pie variant with a center cutout.",
    requiredRoles: ["label", "value"],
    roles: roleSets.pie,
    defaultMapping: { label: "region", value: "profit" },
    defaultSettings: { aggregation: "sum", legendPosition: "right", showLegend: true, cutout: "58%" },
  }),
  createTemplate({
    id: "doughnut-semi",
    family: "doughnut",
    variant: "semi",
    type: "doughnut",
    name: "Semi Doughnut",
    description: "Render a half doughnut for compact summaries.",
    requiredRoles: ["label", "value"],
    roles: roleSets.pie,
    defaultMapping: { label: "category", value: "orders" },
    defaultSettings: { aggregation: "sum", legendPosition: "bottom", showLegend: true, cutout: "62%", semi: true },
  }),
  createTemplate({
    id: "doughnut-multi-ring",
    family: "doughnut",
    variant: "multi-ring",
    type: "doughnut",
    name: "Multi Ring Doughnut",
    description: "Compare multiple measures in concentric rings.",
    requiredRoles: ["label", "measures"],
    roles: roleSets.pie,
    defaultMapping: { label: "region", measures: ["sales", "profit"] },
    defaultSettings: { aggregation: "sum", legendPosition: "right", showLegend: true, cutout: "38%" },
  }),
  createTemplate({
    id: "polar-area-basic",
    family: "polar-area",
    variant: "polar-area",
    type: "polarArea",
    name: "Polar Area",
    description: "Show magnitude around a radial axis.",
    requiredRoles: ["label", "value"],
    roles: roleSets.pie,
    defaultMapping: { label: "region", value: "sales" },
    defaultSettings: { aggregation: "sum", legendPosition: "right", showLegend: true, beginAtZero: true },
  }),
  createTemplate({
    id: "radar-basic",
    family: "radar",
    variant: "basic",
    type: "radar",
    name: "Basic Radar",
    description: "Compare values across multiple indicators.",
    requiredRoles: ["label", "value"],
    roles: roleSets.radar,
    defaultMapping: { label: "category", value: "rating", series: null },
    defaultSettings: { aggregation: "avg", legendPosition: "right", showLegend: true, fill: false, beginAtZero: true },
  }),
  createTemplate({
    id: "radar-filled",
    family: "radar",
    variant: "filled",
    type: "radar",
    name: "Filled Radar",
    description: "Use a filled radar surface for emphasis.",
    requiredRoles: ["label", "value"],
    roles: roleSets.radar,
    defaultMapping: { label: "category", value: "sales", series: null },
    defaultSettings: { aggregation: "sum", legendPosition: "right", showLegend: true, fill: true, beginAtZero: true },
  }),
  createTemplate({
    id: "radar-multi-dataset",
    family: "radar",
    variant: "multi-dataset",
    type: "radar",
    name: "Multi Dataset Radar",
    description: "Compare multiple measures or series in radar form.",
    requiredRoles: ["label"],
    roles: roleSets.radar,
    defaultMapping: { label: "region", value: "sales", series: "category", measures: ["sales", "profit"] },
    defaultSettings: { aggregation: "sum", legendPosition: "right", showLegend: true, fill: false, beginAtZero: true },
  }),
  createTemplate({
    id: "scatter-basic",
    family: "scatter",
    variant: "scatter",
    type: "scatter",
    name: "Scatter",
    description: "Plot two numeric measures against each other.",
    requiredRoles: ["x", "y"],
    roles: roleSets.scatter,
    defaultMapping: { x: "sales", y: "profit", series: null },
    defaultSettings: { aggregation: "sum", legendPosition: "bottom", showLegend: true, beginAtZero: true },
  }),
  createTemplate({
    id: "scatter-multi-series",
    family: "scatter",
    variant: "multi-series",
    type: "scatter",
    name: "Multi Series Scatter",
    description: "Scatter plot grouped into multiple series.",
    requiredRoles: ["x", "y", "series"],
    roles: roleSets.scatter,
    defaultMapping: { x: "sales", y: "profit", series: "region" },
    defaultSettings: { aggregation: "sum", legendPosition: "bottom", showLegend: true, beginAtZero: true },
  }),
  createTemplate({
    id: "bubble-basic",
    family: "bubble",
    variant: "bubble",
    type: "bubble",
    name: "Bubble",
    description: "Plot three measures with bubble size.",
    requiredRoles: ["x", "y", "size"],
    roles: roleSets.bubble,
    defaultMapping: { x: "sales", y: "profit", size: "orders", series: null },
    defaultSettings: { aggregation: "sum", legendPosition: "bottom", showLegend: true, beginAtZero: true },
  }),
  createTemplate({
    id: "bubble-size-comparison",
    family: "bubble",
    variant: "size-comparison",
    type: "bubble",
    name: "Size Comparison Bubble",
    description: "Compare bubble sizes across multiple series.",
    requiredRoles: ["x", "y", "size", "series"],
    roles: roleSets.bubble,
    defaultMapping: { x: "sales", y: "profit", size: "quantity", series: "category" },
    defaultSettings: { aggregation: "sum", legendPosition: "bottom", showLegend: true, beginAtZero: true },
  }),
  createTemplate({
    id: "mixed-bar-line",
    family: "mixed",
    variant: "bar-line",
    type: "bar",
    name: "Bar + Line",
    description: "Overlay a line trend on top of bars.",
    requiredRoles: ["x", "bar", "line"],
    roles: roleSets.mixed,
    defaultMapping: { x: "month", bar: "sales", line: "profit", series: null },
    defaultSettings: { aggregation: "sum", legendPosition: "bottom", showLegend: true, beginAtZero: true, useSecondaryAxis: false, stacked: false },
  }),
  createTemplate({
    id: "mixed-stacked-bar-line",
    family: "mixed",
    variant: "stacked-bar-line",
    type: "bar",
    name: "Stacked Bar + Line",
    description: "Use stacked bars with a single comparison line.",
    requiredRoles: ["x", "bar", "line", "series"],
    roles: roleSets.mixed,
    defaultMapping: { x: "month", bar: "sales", line: "profit", series: "category" },
    defaultSettings: { aggregation: "sum", legendPosition: "bottom", showLegend: true, beginAtZero: true, useSecondaryAxis: false, stacked: true },
  }),
  createTemplate({
    id: "mixed-multi-axis",
    family: "mixed",
    variant: "multi-axis",
    type: "bar",
    name: "Multi Axis Mixed",
    description: "Display bar and line measures on separate axes.",
    requiredRoles: ["x", "bar", "line"],
    roles: roleSets.mixed,
    defaultMapping: { x: "month", bar: "sales", line: "profit", series: null },
    defaultSettings: { aggregation: "sum", legendPosition: "bottom", showLegend: true, beginAtZero: true, useSecondaryAxis: true, stacked: false },
  }),
];

export function getChartJsTemplateById(id) {
  return chartJsTemplates.find((template) => template.id === id) ?? chartJsTemplates[0];
}

export function getChartJsTemplatesByFamily(family) {
  return chartJsTemplates.filter((template) => template.family === family);
}

export function getAllChartJsFamilies() {
  return Array.from(new Set(chartJsTemplates.map((template) => template.family)));
}

export function getChartTypes() {
  return chartJsTemplates.map(({ id, family, variant, type, name, description }) => ({
    id,
    family,
    variant,
    type,
    name,
    description,
  }));
}

