import type { DemoTemplate } from "@modules/dashboards/designer-v2/components/demo/demoTypes";

export const demoTemplates: DemoTemplate[] = [
  {
    id: "sales-overview",
    name: "Sales Overview",
    description: "ภาพรวมยอดขายรายเดือนพร้อมเทียบกำไรสำหรับเดโมผู้บริหาร",
    audience: "ผู้บริหารฝ่ายขาย",
    chartType: "bar",
    themeId: "default-blue",
    sort: "monthOrder",
    mappings: [
      { slotId: "xAxis", fieldIds: ["month"], aggregation: "None" },
      { slotId: "yAxis", fieldIds: ["sales", "profit"], aggregation: "Sum" },
      { slotId: "tooltip", fieldIds: ["category", "channel"], aggregation: "None" },
      { slotId: "value", fieldIds: ["sales"], aggregation: "Sum" },
    ],
    settings: {
      general: {
        title: "ภาพรวมยอดขายรายเดือน",
        subtitle: "ยอดขายและกำไรจากชุดข้อมูล sales_performance",
        padding: 20,
        radius: 4,
      },
      legend: { showLegend: true, position: "top", align: "center", fontSize: 11 },
      labels: { showDataLabels: false },
      axis: { xAxisLabel: "เดือน", yAxisLabel: "ยอดขาย" },
    },
    insights: [
      "ยอดขายเดือนปลายปีสูงกว่าไตรมาสแรกอย่างชัดเจน",
      "กำไรเคลื่อนไหวไปในทิศทางเดียวกับยอดขาย เหมาะสำหรับเล่า trend",
      "เหมาะสำหรับเปิดเดโมก่อนเจาะรายละเอียดตามหมวดหมู่",
    ],
  },
  {
    id: "executive-kpi",
    name: "Executive KPI",
    description: "KPI ยอดขายรวมพร้อมโทนผู้บริหาร",
    audience: "ผู้บริหารระดับสูง",
    chartType: "kpi-card",
    themeId: "executive-dark",
    mappings: [
      { slotId: "value", fieldIds: ["sales"], aggregation: "Sum" },
      { slotId: "target", fieldIds: ["target"], aggregation: "Sum" },
      { slotId: "tooltip", fieldIds: ["profit", "customerCount"], aggregation: "Sum" },
    ],
    settings: {
      general: {
        title: "ยอดขายรวมเทียบเป้าหมาย",
        subtitle: "Executive KPI จากข้อมูลเดโม",
        padding: 24,
        radius: 4,
      },
      legend: { showLegend: false },
      grid: { showGrid: false },
    },
    insights: [
      "ใช้เปิดประชุมผู้บริหารแบบรวดเร็ว",
      "เห็นยอดขายรวมและทิศทางเทียบเป้าหมายทันที",
      "เหมาะกับ Presentation Mode",
    ],
  },
  {
    id: "regional-performance",
    name: "Regional Performance",
    description: "เปรียบเทียบยอดขายตามภูมิภาคและช่องทาง",
    audience: "Regional Manager",
    chartType: "stacked-bar",
    themeId: "business-green",
    sort: "byValueDescending",
    mappings: [
      { slotId: "xAxis", fieldIds: ["region"], aggregation: "None" },
      { slotId: "yAxis", fieldIds: ["sales"], aggregation: "Sum" },
      { slotId: "legend", fieldIds: ["channel"], aggregation: "None" },
      { slotId: "tooltip", fieldIds: ["profit", "quantity"], aggregation: "Sum" },
      { slotId: "value", fieldIds: ["sales"], aggregation: "Sum" },
    ],
    settings: {
      general: {
        title: "ยอดขายตามภูมิภาคและช่องทาง",
        subtitle: "ใช้ดู contribution ของแต่ละช่องทางในแต่ละภูมิภาค",
      },
      legend: { showLegend: true, position: "bottom", align: "center" },
      axis: { xAxisLabel: "ภูมิภาค", yAxisLabel: "ยอดขาย" },
    },
    insights: [
      "เห็น mix ของช่องทางขายในแต่ละภูมิภาคได้ชัด",
      "เหมาะสำหรับคุยแผนขยายช่องทาง",
      "ใช้เทียบ performance ของทีมภูมิภาคได้ทันที",
    ],
  },
  {
    id: "product-analysis",
    name: "Product Analysis",
    description: "สัดส่วนยอดขายตามหมวดหมู่สินค้า",
    audience: "Product Owner",
    chartType: "donut",
    themeId: "premium-purple",
    sort: "byValueDescending",
    mappings: [
      { slotId: "category", fieldIds: ["category"], aggregation: "None" },
      { slotId: "legend", fieldIds: ["category"], aggregation: "None" },
      { slotId: "value", fieldIds: ["sales"], aggregation: "Sum" },
      { slotId: "yAxis", fieldIds: ["sales"], aggregation: "Sum" },
      { slotId: "tooltip", fieldIds: ["profit", "quantity"], aggregation: "Sum" },
    ],
    settings: {
      general: {
        title: "สัดส่วนยอดขายตามหมวดหมู่",
        subtitle: "Donut chart สำหรับเล่า mix สินค้า",
      },
      legend: { showLegend: true, position: "right", align: "center" },
      labels: { showDataLabels: true, position: "outside", fontSize: 11 },
    },
    insights: [
      "เหมาะสำหรับ flow เลือก Donut ในเดโมขาย",
      "เห็นหมวดสินค้าที่สร้างยอดขายหลักโดยไม่ต้องอ่านตาราง",
      "ปิด legend ได้เพื่อโชว์ความยืดหยุ่นของ property panel",
    ],
  },
  {
    id: "customer-insights",
    name: "Customer Insights",
    description: "จำนวนลูกค้าและ conversion ตามช่องทาง",
    audience: "ทีม Customer Success",
    chartType: "line",
    themeId: "warm-orange",
    sort: "monthOrder",
    mappings: [
      { slotId: "xAxis", fieldIds: ["month"], aggregation: "None" },
      { slotId: "yAxis", fieldIds: ["customerCount", "conversionRate"], aggregation: "Sum" },
      { slotId: "legend", fieldIds: ["channel"], aggregation: "None" },
      { slotId: "tooltip", fieldIds: ["sales", "profit"], aggregation: "Sum" },
    ],
    settings: {
      general: {
        title: "ลูกค้าและ Conversion รายเดือน",
        subtitle: "ติดตาม funnel เบื้องต้นจากข้อมูลขาย",
      },
      legend: { showLegend: true, position: "top", align: "center" },
      axis: { xAxisLabel: "เดือน", yAxisLabel: "ลูกค้า / Conversion" },
    },
    insights: [
      "ใช้เล่าเรื่องการเติบโตของฐานลูกค้า",
      "เทียบช่องทางที่มีลูกค้าเยอะกับ conversion ได้ในมุมเดียว",
      "เหมาะสำหรับเดโม filtering ต่อ",
    ],
  },
  {
    id: "financial-summary",
    name: "Financial Summary",
    description: "เทียบยอดขาย ต้นทุน และกำไรในตารางเดียว",
    audience: "Finance",
    chartType: "table",
    themeId: "minimal-gray",
    sort: "monthOrder",
    mappings: [
      { slotId: "rows", fieldIds: ["month", "category", "channel"], aggregation: "None" },
      { slotId: "value", fieldIds: ["sales", "cost", "profit"], aggregation: "Sum" },
      { slotId: "columns", fieldIds: ["category"], aggregation: "None" },
    ],
    settings: {
      general: {
        title: "สรุปการเงินตามเดือน",
        subtitle: "ตารางสำหรับตรวจยอดขาย ต้นทุน และกำไร",
      },
      legend: { showLegend: false },
    },
    insights: [
      "เหมาะกับผู้ใช้ที่ต้องการตรวจตัวเลขละเอียด",
      "ใช้ต่อยอด export CSV ในเดโมได้ดี",
      "ตารางยังอิง mapping และ filter เดียวกับกราฟ",
    ],
  },
  {
    id: "operations-dashboard",
    name: "Operations Dashboard",
    description: "ติดตามจำนวนและเป้าหมายการขาย",
    audience: "Operations",
    chartType: "area",
    themeId: "business-green",
    sort: "monthOrder",
    mappings: [
      { slotId: "xAxis", fieldIds: ["month"], aggregation: "None" },
      { slotId: "yAxis", fieldIds: ["quantity", "target"], aggregation: "Sum" },
      { slotId: "tooltip", fieldIds: ["sales", "cost"], aggregation: "Sum" },
    ],
    settings: {
      general: {
        title: "ปริมาณขายและเป้าหมายรายเดือน",
        subtitle: "มุมมอง operations สำหรับติดตาม capacity",
      },
      legend: { showLegend: true, position: "top", align: "center" },
      axis: { xAxisLabel: "เดือน", yAxisLabel: "จำนวน / เป้าหมาย" },
    },
    insights: [
      "เห็น trend ของปริมาณขายในรอบปี",
      "เหมาะกับการคุยกำลังการผลิตหรือทีมขาย",
      "ใช้ร่วมกับ device preview เพื่อโชว์ responsive ได้",
    ],
  },
  {
    id: "marketing-funnel",
    name: "Marketing Funnel",
    description: "ภาพรวม funnel จาก source ไป target",
    audience: "Marketing",
    chartType: "funnel",
    themeId: "warm-orange",
    sort: "byValueDescending",
    mappings: [
      { slotId: "category", fieldIds: ["source"], aggregation: "None" },
      { slotId: "value", fieldIds: ["flowValue"], aggregation: "Sum" },
      { slotId: "tooltip", fieldIds: ["targetNode", "channel"], aggregation: "None" },
    ],
    settings: {
      general: {
        title: "Marketing Funnel",
        subtitle: "ภาพรวมขั้นตอนจาก Lead ไปจนถึง Won",
      },
      legend: { showLegend: true, position: "right", align: "center" },
    },
    insights: [
      "ใช้โชว์ chart library ที่มากกว่ากราฟพื้นฐาน",
      "อ่าน drop-off ของ funnel ได้เร็ว",
      "เหมาะกับ roadmap การต่อ backend CRM ในอนาคต",
    ],
  },
];
